# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tele3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1128, 861)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.945274 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 20, 611, 81))
        self.label.setStyleSheet("font: 75 22pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));\n"
"color:rgb(0, 0, 0)\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 130, 161, 51))
        self.label_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 200, 161, 51))
        self.label_3.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(100, 270, 161, 51))
        self.label_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 410, 161, 51))
        self.label_5.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(100, 480, 161, 51))
        self.label_6.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(100, 550, 161, 51))
        self.label_7.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(100, 620, 161, 51))
        self.label_8.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(100, 340, 161, 51))
        self.label_9.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(100, 690, 161, 51))
        self.label_10.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(100, 760, 161, 51))
        self.label_11.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"Color:rgb(255, 0, 0)")
        self.label_11.setObjectName("label_11")
        self.inputflength = QtWidgets.QLineEdit(Form)
        self.inputflength.setGeometry(QtCore.QRect(320, 130, 401, 51))
        self.inputflength.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)\n"
"")
        self.inputflength.setObjectName("inputflength")
        self.inputAlpha = QtWidgets.QLineEdit(Form)
        self.inputAlpha.setGeometry(QtCore.QRect(320, 760, 401, 51))
        self.inputAlpha.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)")
        self.inputAlpha.setObjectName("inputAlpha")
        self.inputfM3Trans = QtWidgets.QLineEdit(Form)
        self.inputfM3Trans.setGeometry(QtCore.QRect(320, 690, 401, 51))
        self.inputfM3Trans.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)")
        self.inputfM3Trans.setObjectName("inputfM3Trans")
        self.inputfM3Long = QtWidgets.QLineEdit(Form)
        self.inputfM3Long.setGeometry(QtCore.QRect(320, 620, 401, 51))
        self.inputfM3Long.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)")
        self.inputfM3Long.setObjectName("inputfM3Long")
        self.inputAsym = QtWidgets.QLineEdit(Form)
        self.inputAsym.setGeometry(QtCore.QRect(320, 550, 401, 51))
        self.inputAsym.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)")
        self.inputAsym.setObjectName("inputAsym")
        self.inputfConc1 = QtWidgets.QLineEdit(Form)
        self.inputfConc1.setGeometry(QtCore.QRect(320, 480, 401, 51))
        self.inputfConc1.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)")
        self.inputfConc1.setObjectName("inputfConc1")
        self.inputConc = QtWidgets.QLineEdit(Form)
        self.inputConc.setGeometry(QtCore.QRect(320, 410, 401, 51))
        self.inputConc.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)")
        self.inputConc.setObjectName("inputConc")
        self.inputfSize = QtWidgets.QLineEdit(Form)
        self.inputfSize.setGeometry(QtCore.QRect(320, 340, 401, 51))
        self.inputfSize.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)\n"
"")
        self.inputfSize.setObjectName("inputfSize")
        self.inputfWidth = QtWidgets.QLineEdit(Form)
        self.inputfWidth.setGeometry(QtCore.QRect(320, 270, 401, 51))
        self.inputfWidth.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)")
        self.inputfWidth.setObjectName("inputfWidth")
        self.inputfDist = QtWidgets.QLineEdit(Form)
        self.inputfDist.setGeometry(QtCore.QRect(320, 200, 401, 51))
        self.inputfDist.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0)")
        self.inputfDist.setObjectName("inputfDist")
        self.outputpredict = QtWidgets.QLabel(Form)
        self.outputpredict.setGeometry(QtCore.QRect(830, 480, 151, 51))
        self.outputpredict.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));\n"
"color: rgb(0, 0, 0);")
        self.outputpredict.setObjectName("outputpredict")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(830, 370, 161, 71))
        self.pushButton.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "tele"))
        self.label.setText(_translate("Form", "TELESCOPE SPECTRUM CLASSIFICA"))
        self.label_2.setText(_translate("Form", "flength"))
        self.label_3.setText(_translate("Form", "fDist"))
        self.label_4.setText(_translate("Form", "fWidth"))
        self.label_5.setText(_translate("Form", "fConc"))
        self.label_6.setText(_translate("Form", "fConc1"))
        self.label_7.setText(_translate("Form", "fAsym"))
        self.label_8.setText(_translate("Form", "fM3Long"))
        self.label_9.setText(_translate("Form", "fSize"))
        self.label_10.setText(_translate("Form", "fM3Trans"))
        self.label_11.setText(_translate("Form", "fAlpha"))
        self.outputpredict.setText(_translate("Form", "output"))
        self.pushButton.setText(_translate("Form", "Predict"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
